name: Tests

on: [ push, pull_request ]

jobs:
  unittest:
    strategy:
      matrix:
        go: [ "1.18", oldstable, stable ]
        os: [ ubuntu-24.04-arm, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true # false for self-hosted runners

      - name: Unit Test
        run: go test -race ./...

  benchmark:
    strategy:
      matrix:
        go: [ "1.18", oldstable, stable ]
        os: [ ubuntu-24.04-arm, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true # false for self-hosted runners

      - name: Benchmark
        run: go test -bench=. -benchmem -run=none ./... -benchtime=100ms
